### ISSUE TITLE
Problem installing add-in google-sheet: "Login not verified for this App"

### ISSUE THREAD

**Issue by Derryrover** [lucwastiaux/python-pinyin-jyutping-sentence#3]
Hi thank you for this great tool !

I am using it for several month now to translate from simplified Chinese characters to Pinyin in google sheets.

Anyway, today when doing a fresh install, the install fails.
Google complains that the App is not verified to login.

Thank you for your time.
kr Tom

**Comment by lucwastiaux** [comment]
Hi, can you try the instructions here as a workaround ? https://github.com/lucwastiaux/mandarin-cantonese-api#manually-enabling-the-add-on

**Comment by Derryrover** [comment]
Yes works !
Thank you so much!

**Comment by lucwastiaux** [comment]
Hi, this issue should be corrected now, let me know if you still see a problem.

**Comment by Derryrover** [comment]
Yes I confirm, root cause of the issue is now also fixed. I am now able to install the tool via the add-on installer. Thank you !

**Comment by lucwastiaux** [comment]
Great, thank you !
